Story1/urls.py
from django.urls import path
from . import views

app_name = 'Story1'

urlpatterns = [
    path('', views.biodatappw, name='biodatappw'),

]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('personal/', views.personal, name='personal'),
    path('educational/', views.educational, name='educational'),
    path('Organizational/', views.organizational, name='Organizational'),
    path('thankyou/', views.thankyou, name='thankyou'),

    path('form/', views.form,name = "form"),
    path('form/savename', views.form,name = "form"),
]

ppw4/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls',namespace = 'main')),
    path('Story1/', include('Story1.urls')),
    # path(main/<int:id>,dynamic_lookup_view,name='main-list'),

]

Story1/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models

# Create your models here.
class Matkul(models.Model):
    namaMatkul = models.CharField(max_length=200)
    dosenPengajar= models.CharField(max_length=200)
    jumlahSks= models.CharField(max_length=200)
    deskripsiMatkul=models.CharField(max_length=200)
    semester = models.CharField(max_length=200)
    ruangKelas = models.CharField(max_length=200)
    
    # def get_absolute_url(self):
    #     return f"/main/{self.id}"


class Post(models.Model):
    matkul= models.ForeignKey(Matkul, on_delete = models.CASCADE)
    content = models.CharField(max_length=200)

main/forms.py
from django.forms import ModelForm
from .models import Matkul
from django import forms
class Input_Form(forms.ModelForm):
	class Meta:
		model = Matkul
		fields = ['namaMatkul','dosenPengajar','jumlahSks','deskripsiMatkul','semester','ruangKelas']
	error_messages = {
		'required' : 'Please Type'
	}

	namaMatkul = forms.CharField(label='', required=False, 
    max_length=27)

	jumlahSks = forms.CharField(label='', required=False, 
    max_length=27)

	deskripsiMatkul = forms.CharField(label='', required=False, 
    max_length=27)

	semester = forms.CharField(label='', required=False, 
    max_length=27)

	ruangKelas = forms.CharField(label='', required=False, 
    max_length=27)

Story1/views.py
from django.shortcuts import render

# Create your views here.
def biodatappw(request):
    return render(request,"biodatappw.html")

main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Input_Form

def home(request):
    return render(request, 'main/home.html')
def personal(request):
    return render(request, 'main/personal.html')
def educational(request):
    return render(request, 'main/educational.html')
def organizational(request):
    return render(request, 'main/Organizational.html')
def thankyou(request):
    return render(request, 'main/thankyou.html')
def form(request):
    context={
        'input_form' : Input_Form,
    }
    return render(request, 'main/form.html',context)

def savename(request):
    form = Input_Form(request.POST or None)
    if (form.is_valid and request.method == "POST"):
        form.save()
    return render(request, 'form.html', {'form': form})

Story1/templates/biodatappw.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}

<title> My Biodata </title>
{% endblock meta %}

{% block content %}
<style>
.wrap{
    background-color:rgba(255,255,255,0.7); 
    width: 800px; 
    color:black; 
    margin: 20px auto; 
    padding:15px;
}
</style>
<div class="container ">
<body style="background-color:#f1e0af;">
    <div class="wrap">
        <h1 style = "color: blcak; margin-top: 50px" class="class" align="center">BIODATA DIRI<h1><hr/ align="center"width="25% style="border-top: 3px double #353535;">
<table>
<tr><td rowspan="20" width="50px">
<img SRC="{% static 'halweb.jpeg' %}" width="200px" style="display: block;border-radius:25%;border-color:rgb(110, 110, 110);margin-right:30px" border="2px" ></td></tr>
<tr><td><b>Nama</b></td><td>:</td> <td>Fayza Hanifah</td></tr>
<tr><td><b>NPM</b></td><td>:</td> <td>1906399726</td></tr>
<tr><td><b>Tempat Kuliah</b></td><td>:</td> <td>Universitas Indonesia</td></tr>
<tr><td><b>Angkatan</b></td><td>:</td> <td>2019</td></tr>
<tr><td><b>Hobi</b></td><td>:</td> <td>Photography</td></tr>
<tr><td><b>Deskripsi tentang saya</b></td><td>:</td> <td>An ambivert girl</td></tr>
<tr><td><b>Media Sosial</b></td><td>:</td> <td> ig: fhanifah_</td></tr></table>

<table>
<h3> Riwayat Pendidikan</h3>
<tr><td><b>SD</b></td><td>:</td> <td>SDIT Qurrata A'yun</td></tr>
<tr><td><b>SMP</b></td><td>:</td> <td>SMPN 5 Batusangkar</td></tr>
<tr><td><b>SMA</b></td><td>:</td> <td>SMAN 1 Batusangkar</td></tr></table>
</div>
</body>
</div>

    

{% endblock content %}

main/templates/main/Organizational.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Welcome to my Website </title>
{% endblock meta %}


{% block content %}    
    <body style="background-color:#f1e0af;">
        
            <div class="container">
                <h1 style = "color: blcak; margin-top: 50px" class="p-3 mb-2 bg-warning text-dark text-center">Organizational Experience</h1>
                    <p class="lead text-center">I have joined the FUKI organization since early 2020 until now as a MUC staff</p>
                        <div class="text-center">
                            <img src="{% static 'img/fuki.png' %}" class= "img-thumbnail">
        
                        </div>
            </div>
{% endblock content %}

main/templates/main/educational.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Welcome to my Website </title>
{% endblock meta %}

{% block content %}
    <body style="background-color:#cc9c44;"></body>
       
            <div class="container">
                <h1 style = "color: blcak; margin-top: 50px" class="p-3 mb-2 bg-warning text-dark text-center">Educational Backround </h1>
                    <p class="lead text-center"> So there are my educational backround :)</p>
                        <div class="col-md-12">
                
                            <h2>
                                <table>
                                    <tr><td><b>2007-2013</b></td><td>:</td> <td>Qurrata A'yun Elementary School Batusangkar</td></tr>
                                    <tr><td><b>2013-2016</b></td><td>:</td> <td>State Junior High School 5, Batusangkar</td></tr>
                                    <tr><td><b>2016-2019</b></td><td>:</td> <td>State Senior High School 1, Batusangkar</td></tr>
                                    <tr><td><b>2019-now</b></td><td>:</td> <td>University of Indonesia</td></tr></table>
                                </table>
                            </h2>
        
                        </div>


{% endblock content %}

main/templates/main/form.html
{% extends 'base.html' %}

{% block content %}
<h1 style = "color: blcak; margin-top: 50px" class="p-3 mb-2 bg-warning text-dark text-center">Welcome to My Website</h1>
<form action="savename" method="POST">
    {% csrf_token%}
    <br>Nama Matkul: {{ input_form.namaMatkul }}<br>
    <br>Dosen Pengajar: {{ input_form.dosenPengajar}}<br>
    <br>Jumlah SKS: {{ input_form.jumlahSks}}<br>
    <br>Deskripsi Matkul: {{ input_form.deskripsiMatkul }}<br>
    <br>Semester: {{ input_form.semester }}<br>
    <br>Ruang Kelas: {{ input_form.ruangKelas }}<br>



    <input type="submit" value="Submit">
  </form>
{% endblock %}
<!-- 
namaMatkul = models.CharField(max_length=200)
dosenPengajar= models.CharField(max_length=200)
jumlahSks= models.CharField(max_length=200)
deskripsiMatkul=models.CharField(max_length=200)
semester = models.CharField(max_length=200)
ruangKelas = models.CharField(max_length=200) -->

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
  <title>Welcome to my Website </title>

{% endblock meta %}

{% block content %}

    <!-- Button halaman utama -->
    <body style="background-color:#cc9c44;">
    
    <!-- Penutup button halaman utama -->
        <div class="container text-center">
          <h1 style = "color: blcak; margin-top: 50px" class="p-3 mb-2 bg-warning text-dark text-center">Welcome to My Website</h1>
                <img src="{% static 'img/Homee.jpg' %}" alt="" class="img-thumbnail">

                
            </div>
        </div>
    
    <!-- Image and text -->
    <nav class="navbar navbar-light bg-light">
      <a class="navbar-brand" href="https://www.instagram.com/fhanifah_/">
        <img src="{% static 'img/instagramfix.svg' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        Instagram
      </a>
      <a class="navbar-brand" href="mailto:fayzahanifahh@gmail.com">
        <img src="{% static 'img/Gmail.svg' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        Email
      </a>
      <a class="navbar-brand" href="https://api.whatsapp.com/send?phone=081371342063">
        <img src="{% static 'img/wa.svg' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        Whats App
      </a>
    <!-- </nav>
    <form action="savename" method="POST">
      {% csrf_token%}
      Name : {{ input_form.as_p}}
      <input type="submit" value="Submit>">
    </form>
   -->
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2020 Copyright:
      <a href="https://mdbootstrap.com/"> MDBootstrap.com</a>
    </div>
    </body>
    <!-- Copyright -->
{% endblock content %}
  


        
    

main/templates/main/matakuliah.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Welcome to my Website </title>
{% endblock meta %}


{% block content %}    
    <body style="background-color:#f1e0af;">
        
        <div class="list-group">
            <!-- {% for instance in object_list %}
            <p>{{instance.id}} - <a href='{{instance.get_absolute_url}}'>{{instance.title}}</a></p>
            {% endfor} -->
            <!-- <a href="1" class="list-group-item list-group-item-action">MPK-Agama</a>
            <a href="2" class="list-group-item list-group-item-action">DASAR-DASAR ARSITEKTUR KOMPUTER</a>
            <a href="3" class="list-group-item list-group-item-action">PEMROGRAMAN & PERANCANGAN WEB</a>
            <a href="4" class="list-group-item list-group-item-action disabled">ADMINISTRASI BISNIS</a>
            <a href="5" class="list-group-item list-group-item-action disabled">PRINSIP-PRINSIP MANAJEMEN</a>
            <a href="6" class="list-group-item list-group-item-action disabled">MATEMATIKA DISKRET</a>
            <a href="7" class="list-group-item list-group-item-action disabled">DASAR-DASAR PEMROGRAMAN 2</a> -->
          </div>
{% endblock content %}

main/templates/main/personal.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}   
<title>Welcome to my Website </title>
{% endblock meta %}

{% block content %}
    <body style="background-color:#f1e0af;">
        
            <div class="container">
                <h1 style = "color: blcak; margin-top: 50px" style = "color: blcak; margin-top: 50px" class="p-3 mb-2 bg-warning text-dark text-center">Personal Information</h1>
                    <p class="lead text-center">So,this is a bit about my personal information :)</p>
                    <div class="row">
                        <div class="col-md-4">
                            <img src="{% static 'img/foto.jpeg' %}" alt="" class="img-thumbnail">
                        </div>
                        <div class="col-md-6">
                            
                            <h2>
                            <table>
                            <tbody><tr><td><b>Nama</b></td><td>:</td> <td>Fayza Hanifah</td></tr>
                            <tr><td><b>NPM</b></td><td>:</td> <td>1906399726</td></tr>
                            <tr><td><b>Tempat Kuliah</b></td><td>:</td> <td>Universitas Indonesia</td></tr>
                            <tr><td><b>Angkatan</b></td><td>:</td> <td>2019</td></tr>
                            <tr><td><b>Hobi</b></td><td>:</td> <td>Photography</td></tr>
                            <tr><td><b>Deskripsi tentang saya</b></td><td>:</td> <td>An ambivert girl</td></tr>
                            <tr><td><b>Media Sosial</b></td><td>:</td> <td> ig: fhanifah_</td></tr>
                           </tbody></table></h2>
                        
                        </div>
                    </div>
{% endblock content %}
                 

main/templates/main/thankyou.html
{% extends 'base.html' %}
{% load static %}

{% block meta %} 
<title>Welcome to my Website </title>
{% endblock meta %}

{% block content %}

    <body style="background-color:#cc9c44;">
        
                <h1 style = "color: blcak; margin-top: 50px" class= "p-3 mb-2 bg-warning text-dark text-center">My Hobby </h1>
                    <p class="lead text-center"> So there are some pict of my capture :)</p>

                            <div class="row">
                                <div class="col-sm-4">
                                    <img src="{% static 'img/1.jpeg' %}" alt="" class="img-thumbnail">

                                  </a>  
                                </div>
                                <div class="col-sm-4">
                                    <img src="{% static 'img/2.jpeg' %}" alt="" class="img-thumbnail">

                                  </a>  
                                </div>
                                <div class="col-sm-4">
                                    <img src="{% static 'img/3.jpeg' %}"alt="" class="img-thumbnail">

                                  </a>  
                                </div>
                                <div class="col-sm-4">
                                    <img src="{% static 'img/4.jpeg' %}" alt="" class="img-thumbnail">

                                  </a>  
                                </div>
                                <div class="col-sm-4">
                                    <img src="{% static 'img/5.jpeg' %}" alt="" class="img-thumbnail">

                                  </a>  
                                </div>
                                <div class="col-sm-4">
                                    <img src="{% static 'img/6.jpeg' %}" alt="" class="img-thumbnail">

                                  </a>  
                                </div>
                                
                                
                            </div>

                        
{% endblock content %}
                                    
                                
                            

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" 
  integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style2.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark" style="background-color:#444242;">
			<a class="navbar-brand" href="{% url 'main:home' %}#about">Home</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			  <span class="navbar-toggler-icon"></span>
			</button>
		  
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
			  <ul class="navbar-nav mr-auto">

				<li class="nav-item active">
				  <a class="nav-link" href="{% url 'main:personal' %}">Personal</a>
				</li>
				<li class="nav-item active">
					<a class="nav-link" href="{% url 'main:educational' %}">Education</a>
				</li>
				<li class="nav-item active">
					<a class="nav-link" href="{% url 'main:Organizational' %}">Organizational</a>
                </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'main:thankyou' %}">Hobby</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'main:form' %}">Form</a>
          </li>

          <li class="nav-item active">
            <a class="nav-link" href="{% url 'Story1:biodatappw' %}">Biodata</a>
          </li>
          
        </ul>
        </div>
        </nav>
      
{% block content %}
{% endblock content %}     




</body>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>  
</html>